image: python:3.9-slim

variables:
  ENVIRONMENT_NAME: startup-campus-backend

stages:
  - grade

before_script:
  - python --version # For debugging
  - python3.9 -m pip install virtualenv
  - python3.9 -m venv $ENVIRONMENT_NAME
  - source $ENVIRONMENT_NAME/bin/activate
  - python3.9 -m pip install -r requirements.txt
  - pwd && ls # for debugging

# grade-assignment1:
#   stage: grade
#   script:
#     - cd Assignments/Assignment1
#     - python3.9 -m grader

# grade-assignment2:
#   stage: grade
#   script:
#     - cd Assignments/Assignment2
#     - python3.9 -m grader

# grade-project1:
#   stage: grade
#   script:
#     - cd Projects/Project1
#     - python3.9 -m grader

grade-assignment3:
  stage: grade
  script:
    - cd Assignments/Assignment3
    - python3.9 -m grader
