from random import choices


count_videos = [
    [10, 156],
    [-5, 0],
    *choices(
        [
            [1, 18],
            [2, 34],
            [3, 54],
            [4, 76],
            [5, 88],
            [6, 103],
            [7, 109],
            [8, 123],
            [9, 137],
            [10, 156],
            [11, 176],
            [12, 190],
            [13, 208],
            [14, 231],
            [15, 254],
            [16, 270],
            [17, 292],
            [18, 308],
            [19, 333],
            [20, 345],
            [21, 364],
            [22, 383],
            [23, 402],
            [24, 426],
            [25, 442],
            [26, 454],
            [27, 469],
            [28, 486],
            [29, 506],
            [30, 524],
            [31, 537],
            [32, 550],
            [33, 565],
            [34, 582],
            [35, 601],
            [36, 620],
            [37, 640],
            [38, 651],
            [39, 664],
            [40, 676],
            [41, 696],
            [42, 707],
            [43, 726],
            [44, 740],
            [45, 756],
            [46, 774],
            [47, 790],
            [48, 808],
            [49, 820],
            [50, 837],
            [51, 855],
            [52, 875],
            [53, 887],
            [54, 903],
            [55, 921],
            [56, 943],
            [57, 959],
            [58, 974],
            [59, 988],
        ],
        k=5,
    ),
    [60, 1000],
    [100, 1000],
]


_oldest_n_videos = [
    "Triangulum Ft woodside cohosh pendulous downstream opal buckthorn sundown",
    "bedimmed murder serve mascara Dryden declivity lingerie battle",
    "Coddington churn rockaway Knott algae fluke osprey star",
    "springtime physiochemical reputation tabletop Pearce",
    "econometric reed Greenblatt scrupulous Waltham apogee inoperative townsmen confiscatory",
    "twaddle Rachmaninoff switchgear inheritor rapprochement pitchblende loge assignee",
    "Mildred Scheherazade decile weed along missive Merle Judith",
    "saddle Fresnel peck hollowware charcuterie windbreak Zagreb Marlowe",
    "shoreline aide surrogate empty genteel toady",
    "Coleman scab burly obstruent Barth embarrass Lombardy",
    "pastry catnip Wyatt blotch conceive gabardine translate diplomacy automat signboard",
    "Everett progression silk mark marshal Zion sprig amatory Volstead",
    "headdress haploidy platitude sultry tapa anthropocentric knelt Catherine umbra devastate",
    "sacrament Dewey Eben Higgins piloerection complainant lest",
    "joust gander kale alb illiteracy renounce homebuilder reek",
    "loris ask composition canton seductive diorite breakneck failsoft slack",
    "starlight brainwash dictatorial appanage practitioner inconspicuous discuss",
    "supremacy open value aid bucket",
    "mestizo Albania Mardi purse placebo persecution deity Saigon mud ptarmigan",
    "brunch peer crimp invent animosity basalt e'er",
    "bin skylark viii mendacity Maxine knack inch",
    "clamber bear forgotten Halley dust atone handclasp motherland fortnight abstinent",
    "dial aria school Vladimir gigging",
    "Guelph rather sob spooky histrionic transition acrimonious rule sanction",
    "fought Lockheed predacious whittle commonwealth shadowy killdeer leachate permissible comport",
    "Carlyle incline headroom Oberlin impeller auditor Antonio Rangoon",
    "sidewall tempt bolometer legacy lace luxurious Cooke tug Neff countervail",
    "Deere Cupid supranational tramp forgettable Etruria",
    "despotic snarl socioeconomic vertebral jig hegemony",
    "transliterate hummingbird suspect plank flush articulate cladophora",
    "dome in prismatic Dunham eventuate Goldman Gary swidden scrabble lurk",
    "scarce Anna wasteland breastwork Lowry",
    "Rensselaer midwives rescue start inelastic chameleon bundle doorman Perkins",
    "tuberculin viola pyrolysis salon until Nicodemus Glendale",
    "at arctangent pornography lye seasonal pursuit ahead",
    "congenial anisotropy chalcocite dicotyledon Fe caprice involute fullback",
    "viva nomograph diaper card Saunders cerise victory",
    "McKenna democrat Oregon urinary cutover Gibson",
    "frontier campsite strange satyr argo fallacy diehard Haifa wakerobin",
    "peste handmaiden length Aegean supple assure advocate",
    "Joaquin oasis assurance wobble numeric ITT centipede shore Gonzales petite",
    "teethe cohort secret Strickland bright extirpate don't pornographer",
    "rush Ilona raj Rudyard roil rattlesnake covary stingy ceremony vampire",
    "issuant ploy stake russet chitin destruct inadvertent hooch",
    "throughout shiv gorgon Tartary prestige",
    "phenolic fit allusion Araby French equip combinatorial uremia driveway errata",
    "Dnieper livid leak buffoon digress watch fat",
    "Whatley fourth limpet Gonzales Prague Sturm archival devise",
    "supremacy ocular forward umbrage oppression Stonehenge",
    "flocculate cockle lossy eschew troposphere Bailey vagabond Alfredo",
    "vesicular separable moist mixture referendum sagacious lama interrogatory",
    "Durer emeritus marshy neoprene Wotan commendatory McElroy moneymake",
    "geothermal windstorm withdrawn stipple Cambrian",
    "ducat neodymium sphere sextet Mogadiscio Dan sentry antler",
]
oldest_videos = [
    [1, [_oldest_n_videos[0]]],
    *[[n, _oldest_n_videos[:n]] for n in choices(range(1, 51), k=4)],
]

_most_watched_n_videos = [
    "headdress haploidy platitude sultry tapa anthropocentric knelt Catherine umbra devastate",
    "Buchwald Huntington legislature drove ovary hightail ibid",
    "McKenna democrat Oregon urinary cutover Gibson",
    "twaddle Rachmaninoff switchgear inheritor rapprochement pitchblende loge assignee",
    "mestizo Albania Mardi purse placebo persecution deity Saigon mud ptarmigan",
    "Guelph rather sob spooky histrionic transition acrimonious rule sanction",
    "obstruct Univac typology sowbug fluent",
    "stronghold rakish wintergreen amphibole Lesotho mantelpiece dumbbell",
    "springtime physiochemical reputation tabletop Pearce",
    "sacrament Dewey Eben Higgins piloerection complainant lest",
    "auditorium comprehension lessee inferential Americana domestic Huxley AAA",
    "sigma dactyl bellyful habit eft impenetrable miraculous declination Polaris Edna",
    "peste handmaiden length Aegean supple assure advocate",
    "Whatley fourth limpet Gonzales Prague Sturm archival devise",
    "sentence insolate procrustean safe manometer cudgel conduit herewith",
    "bedimmed murder serve mascara Dryden declivity lingerie battle",
    "econometric reed Greenblatt scrupulous Waltham apogee inoperative townsmen confiscatory",
    "Kim bluebird cocktail leitmotif stagnant wag captaincy foe cosponsor grim",
    "fibration languid belladonna patchy vulgar",
    "Coleman scab burly obstruent Barth embarrass Lombardy",
    "loris ask composition canton seductive diorite breakneck failsoft slack",
    "despotic snarl socioeconomic vertebral jig hegemony",
    "rush Ilona raj Rudyard roil rattlesnake covary stingy ceremony vampire",
    "coxcomb flash scrutiny indeterminacy Irvine elution amphioxis corpse",
    "riboflavin spermatophyte typeface corrugate memoranda trillion fumigant",
]
most_watched_videos = [
    [1, [_most_watched_n_videos[0]]],
    *[[n, _most_watched_n_videos[:n]] for n in choices(range(1, 26), k=5)],
]

_most_active_n_users = [
    ["Francis Frank", 911.0],
    ["Renee Fitzgerald", 825.0],
    ["Rylee Giles", 815.0],
    ["Jakob Wolfe", 796.0],
    ["Paris Moon", 783.0],
    ["Ezekiel Glenn", 782.0],
    ["Victoria Woods", 774.0],
    ["Jocelyn Newman", 756.0],
    ["Emilie Barron", 745.0],
    ["Jaylin Mckee", 736.0],
    ["Howard Carson", 733.0],
    ["Molly Byrd", 726.0],
    ["Sincere Greer", 721.0],
    ["Marin Baxter", 706.0],
    ["Clarence Alvarado", 703.0],
    ["Hayden Warren", 698.0],
    ["Darryl Gordon", 698.0],
    ["Antoine Mccullough", 698.0],
    ["Logan Bowen", 695.0],
    ["Darnell Andersen", 689.0],
    ["Donte Hodges", 686.0],
    ["Leila Esparza", 679.0],
    ["Noemi English", 678.0],
    ["Jaylee Hunter", 677.0],
    ["Nehemiah Terry", 676.0],
    ["Dayana Jensen", 674.0],
    ["Cassie Mcgrath", 671.0],
    ["King Watkins", 664.0],
    ["Kaleigh Fitzgerald", 660.0],
    ["Mallory Johnson", 659.0],
    ["Ashley Hardy", 659.0],
    ["Jovan Hardin", 659.0],
    ["Colt Duarte", 647.0],
    ["Blaine Sharp", 645.0],
    ["Penelope Hunter", 642.0],
    ["Veronica Pace", 639.0],
    ["Evan Terry", 639.0],
    ["Ainsley Welch", 638.0],
    ["Brittany Cook", 637.0],
    ["Ronin Jennings", 637.0],
    ["Katie Hawkins", 636.0],
    ["Edith Lowery", 632.0],
    ["Yuliana Mcknight", 632.0],
    ["Juan May", 630.0],
    ["Taylor Kline", 627.0],
    ["Jace Grimes", 626.0],
    ["Adalynn Salinas", 625.0],
    ["Paige Yoder", 623.0],
    ["Jewel Patterson", 621.0],
    ["Jamie Fry", 620.0],
    ["Jakayla Camacho", 620.0],
    ["Arielle Harper", 619.0],
    ["Triston Rojas", 618.0],
    ["Terrell Calhoun", 617.0],
    ["Rowan Booker", 617.0],
    ["Juliette Camacho", 616.0],
    ["Atticus Sparks", 613.0],
    ["Elias Crawford", 611.0],
    ["Adolfo Mathews", 610.0],
    ["Sydnee Hoffman", 610.0],
    ["Trevin Joseph", 606.0],
    ["Beatrice Richardson", 604.0],
    ["Elaina Melton", 603.0],
    ["Luciana Whitney", 602.0],
    ["Gilberto Arroyo", 601.0],
    ["Patience Roberts", 599.0],
    ["Scott Bowen", 597.0],
    ["Jacquelyn Jimenez", 597.0],
    ["Christine Watkins", 596.0],
    ["Amiya Lopez", 594.0],
    ["Francisco Roy", 593.0],
    ["Audrina Hodge", 593.0],
    ["Zachariah Lucero", 590.0],
    ["Brett Cline", 590.0],
    ["Aracely Vincent", 590.0],
    ["Quinton Pena", 590.0],
    ["Alanna Browning", 587.0],
    ["Chase Cook", 584.0],
    ["Paris Watts", 583.0],
    ["Nina Higgins", 581.0],
    ["Micah Freeman", 576.0],
    ["Brody Ponce", 574.0],
    ["Gustavo Bullock", 572.0],
    ["Cedric Vazquez", 571.0],
    ["Miah Stewart", 570.0],
    ["Liliana Donaldson", 569.0],
    ["Karli Dyer", 565.0],
    ["Giovanni Moyer", 565.0],
    ["Makhi Barton", 563.0],
    ["Zane Bauer", 562.0],
    ["Blake Tate", 560.0],
    ["Cindy Craig", 557.0],
    ["Brycen Chang", 555.0],
    ["Dixie Paul", 553.0],
    ["Reuben Bridges", 553.0],
    ["Stephen Chan", 551.0],
    ["Zachary Schneider", 549.0],
    ["Armando Sutton", 548.0],
    ["Rayan Macias", 546.0],
    ["Carla Peters", 545.0],
]
most_active_users = [
    [3, _most_active_n_users[:3]],
    *[[n, _most_active_n_users[:n]] for n in choices(range(1, 101), k=10)],
]

_least_watched_n_categories = [
    "Film & Animation",
    "Howto & Style",
    "Entertainment",
    "Comedy",
    "People & Blogs",
    "Autos & Vehicles",
    "Pets & Animals",
    "Travel & Events",
    "Nonprofits & Activism",
    "Sports",
    "Science & Technology",
    "Gaming",
    "News & Politics",
    "Music",
    "Education",
]
least_watched_categories = [
    [1, [_least_watched_n_categories[0]]],
    *[[n, _least_watched_n_categories[:n]] for n in choices(range(1, 11), k=5)],
]
