from random import choices


count_videos = [
    [10, 156],
    [-5, 0],
    *choices(
        [
            [1, 18],
            [2, 34],
            [3, 54],
            [4, 76],
            [5, 88],
            [6, 103],
            [7, 109],
            [8, 123],
            [9, 137],
            [10, 156],
            [11, 176],
            [12, 190],
            [13, 208],
            [14, 231],
            [15, 254],
            [16, 270],
            [17, 292],
            [18, 308],
            [19, 333],
            [20, 345],
            [21, 364],
            [22, 383],
            [23, 402],
            [24, 426],
            [25, 442],
            [26, 454],
            [27, 469],
            [28, 486],
            [29, 506],
            [30, 524],
            [31, 537],
            [32, 550],
            [33, 565],
            [34, 582],
            [35, 601],
            [36, 620],
            [37, 640],
            [38, 651],
            [39, 664],
            [40, 676],
            [41, 696],
            [42, 707],
            [43, 726],
            [44, 740],
            [45, 756],
            [46, 774],
            [47, 790],
            [48, 808],
            [49, 820],
            [50, 837],
            [51, 855],
            [52, 875],
            [53, 887],
            [54, 903],
            [55, 921],
            [56, 943],
            [57, 959],
            [58, 974],
            [59, 988],
        ],
        k=5,
    ),
    [60, 1000],
    [100, 1000],
]


_oldest_n_videos = [
    "Triangulum Ft woodside cohosh pendulous downstream opal buckthorn sundown",
    "bedimmed murder serve mascara Dryden declivity lingerie battle",
    "Coddington churn rockaway Knott algae fluke osprey star",
    "springtime physiochemical reputation tabletop Pearce",
    "econometric reed Greenblatt scrupulous Waltham apogee inoperative townsmen confiscatory",
    "twaddle Rachmaninoff switchgear inheritor rapprochement pitchblende loge assignee",
    "Mildred Scheherazade decile weed along missive Merle Judith",
    "saddle Fresnel peck hollowware charcuterie windbreak Zagreb Marlowe",
    "shoreline aide surrogate empty genteel toady",
    "Coleman scab burly obstruent Barth embarrass Lombardy",
    "pastry catnip Wyatt blotch conceive gabardine translate diplomacy automat signboard",
    "Everett progression silk mark marshal Zion sprig amatory Volstead",
    "headdress haploidy platitude sultry tapa anthropocentric knelt Catherine umbra devastate",
    "sacrament Dewey Eben Higgins piloerection complainant lest",
    "joust gander kale alb illiteracy renounce homebuilder reek",
    "loris ask composition canton seductive diorite breakneck failsoft slack",
    "starlight brainwash dictatorial appanage practitioner inconspicuous discuss",
    "supremacy open value aid bucket",
    "mestizo Albania Mardi purse placebo persecution deity Saigon mud ptarmigan",
    "brunch peer crimp invent animosity basalt e'er",
    "bin skylark viii mendacity Maxine knack inch",
    "clamber bear forgotten Halley dust atone handclasp motherland fortnight abstinent",
    "dial aria school Vladimir gigging",
    "Guelph rather sob spooky histrionic transition acrimonious rule sanction",
    "fought Lockheed predacious whittle commonwealth shadowy killdeer leachate permissible comport",
    "Carlyle incline headroom Oberlin impeller auditor Antonio Rangoon",
    "sidewall tempt bolometer legacy lace luxurious Cooke tug Neff countervail",
    "Deere Cupid supranational tramp forgettable Etruria",
    "despotic snarl socioeconomic vertebral jig hegemony",
    "transliterate hummingbird suspect plank flush articulate cladophora",
    "dome in prismatic Dunham eventuate Goldman Gary swidden scrabble lurk",
    "scarce Anna wasteland breastwork Lowry",
    "Rensselaer midwives rescue start inelastic chameleon bundle doorman Perkins",
    "tuberculin viola pyrolysis salon until Nicodemus Glendale",
    "at arctangent pornography lye seasonal pursuit ahead",
    "congenial anisotropy chalcocite dicotyledon Fe caprice involute fullback",
    "viva nomograph diaper card Saunders cerise victory",
    "McKenna democrat Oregon urinary cutover Gibson",
    "frontier campsite strange satyr argo fallacy diehard Haifa wakerobin",
    "peste handmaiden length Aegean supple assure advocate",
    "Joaquin oasis assurance wobble numeric ITT centipede shore Gonzales petite",
    "teethe cohort secret Strickland bright extirpate don't pornographer",
    "rush Ilona raj Rudyard roil rattlesnake covary stingy ceremony vampire",
    "issuant ploy stake russet chitin destruct inadvertent hooch",
    "throughout shiv gorgon Tartary prestige",
    "phenolic fit allusion Araby French equip combinatorial uremia driveway errata",
    "Dnieper livid leak buffoon digress watch fat",
    "Whatley fourth limpet Gonzales Prague Sturm archival devise",
    "supremacy ocular forward umbrage oppression Stonehenge",
    "flocculate cockle lossy eschew troposphere Bailey vagabond Alfredo",
    "vesicular separable moist mixture referendum sagacious lama interrogatory",
    "Durer emeritus marshy neoprene Wotan commendatory McElroy moneymake",
    "geothermal windstorm withdrawn stipple Cambrian",
    "ducat neodymium sphere sextet Mogadiscio Dan sentry antler",
]
oldest_videos = [
    [1, [_oldest_n_videos[0]]],
    *[[n, _oldest_n_videos[:n]] for n in choices(range(1, 51), k=4)],
]

_most_watched_n_videos = [
    "headdress haploidy platitude sultry tapa anthropocentric knelt Catherine umbra devastate",
    "Buchwald Huntington legislature drove ovary hightail ibid",
    "McKenna democrat Oregon urinary cutover Gibson",
    "twaddle Rachmaninoff switchgear inheritor rapprochement pitchblende loge assignee",
    "mestizo Albania Mardi purse placebo persecution deity Saigon mud ptarmigan",
    "Guelph rather sob spooky histrionic transition acrimonious rule sanction",
    "obstruct Univac typology sowbug fluent",
    "stronghold rakish wintergreen amphibole Lesotho mantelpiece dumbbell",
    "springtime physiochemical reputation tabletop Pearce",
    "sacrament Dewey Eben Higgins piloerection complainant lest",
    "auditorium comprehension lessee inferential Americana domestic Huxley AAA",
    "sigma dactyl bellyful habit eft impenetrable miraculous declination Polaris Edna",
    "peste handmaiden length Aegean supple assure advocate",
    "Whatley fourth limpet Gonzales Prague Sturm archival devise",
    "sentence insolate procrustean safe manometer cudgel conduit herewith",
    "bedimmed murder serve mascara Dryden declivity lingerie battle",
    "econometric reed Greenblatt scrupulous Waltham apogee inoperative townsmen confiscatory",
    "Kim bluebird cocktail leitmotif stagnant wag captaincy foe cosponsor grim",
    "fibration languid belladonna patchy vulgar",
    "Coleman scab burly obstruent Barth embarrass Lombardy",
    "loris ask composition canton seductive diorite breakneck failsoft slack",
    "despotic snarl socioeconomic vertebral jig hegemony",
    "rush Ilona raj Rudyard roil rattlesnake covary stingy ceremony vampire",
    "coxcomb flash scrutiny indeterminacy Irvine elution amphioxis corpse",
    "riboflavin spermatophyte typeface corrugate memoranda trillion fumigant",
]
most_watched_videos = [
    [1, [_most_watched_n_videos[0]]],
    *[[n, _most_watched_n_videos[:n]] for n in choices(range(1, 26), k=5)],
]

_most_active_n_users = [
    ["Jocelyn Newman", 1691],
    ["Marin Baxter", 1548],
    ["Howard Carson", 1539],
    ["Francis Frank", 1504],
    ["Jakob Wolfe", 1497],
    ["Donte Hodges", 1441],
    ["Rylee Giles", 1427],
    ["Renee Fitzgerald", 1427],
    ["Sincere Greer", 1399],
    ["Hayden Warren", 1388],
    ["Antoine Mccullough", 1377],
    ["Katie Hawkins", 1377],
    ["Molly Byrd", 1370],
    ["Ezekiel Glenn", 1355],
    ["Victoria Woods", 1352],
    ["Clarence Alvarado", 1341],
    ["Elaina Melton", 1313],
    ["Jaylin Mckee", 1310],
    ["Nehemiah Terry", 1307],
    ["Triston Rojas", 1300],
    ["Adolfo Mathews", 1286],
    ["Ronin Jennings", 1268],
    ["Penelope Hunter", 1267],
    ["Cassie Mcgrath", 1257],
    ["Logan Bowen", 1254],
    ["Paris Moon", 1246],
    ["Emilie Barron", 1241],
    ["King Watkins", 1234],
    ["Francisco Roy", 1234],
    ["Brittany Cook", 1230],
    ["Blaine Sharp", 1224],
    ["Juan May", 1222],
    ["Gilberto Arroyo", 1221],
    ["Miah Stewart", 1220],
    ["Yuliana Mcknight", 1219],
    ["Jovan Hardin", 1219],
    ["Nina Higgins", 1218],
    ["Hailee Kim", 1213],
    ["Paris Watts", 1212],
    ["Haleigh Hamilton", 1210],
    ["Liliana Donaldson", 1208],
    ["Noemi English", 1206],
    ["Micah Freeman", 1200],
    ["Luciana Whitney", 1196],
    ["Beatrice Richardson", 1195],
    ["Atticus Sparks", 1195],
    ["Amelia Key", 1194],
    ["Paige Yoder", 1193],
    ["Ainsley Welch", 1192],
    ["Jovany Orozco", 1189],
    ["Mallory Johnson", 1188],
    ["Abigail Kennedy", 1188],
    ["Julie Ashley", 1183],
    ["Darnell Andersen", 1175],
    ["Alec Mitchell", 1172],
    ["Jewel Patterson", 1166],
    ["Yael Trujillo", 1165],
    ["Jacquelyn Jimenez", 1160],
    ["Audrina Hodge", 1160],
    ["Jamie Fry", 1159],
    ["Landyn Blevins", 1158],
    ["Tiffany Mclean", 1156],
    ["Rowan Booker", 1154],
    ["Jakayla Camacho", 1153],
    ["Elias Crawford", 1153],
    ["Marcelo Werner", 1149],
    ["Edith Lowery", 1149],
    ["Hadley Mcgee", 1146],
    ["Brody Ponce", 1146],
    ["Keon Vega", 1146],
    ["Darryl Gordon", 1146],
    ["Annie Barnett", 1137],
    ["Kimberly Wilson", 1136],
    ["Lilia Reynolds", 1129],
    ["Mylie Randall", 1126],
    ["Dayana Jensen", 1124],
    ["Jaylee Hunter", 1121],
    ["Rory Vargas", 1119],
    ["Evan Terry", 1117],
    ["Jace Grimes", 1111],
    ["Paxton Moran", 1109],
    ["Colt Duarte", 1104],
    ["Maximus Mcfarland", 1103],
    ["Leila Esparza", 1103],
    ["Armando Sutton", 1100],
    ["Rayan Macias", 1091],
    ["Brett Cline", 1089],
    ["Scott Bowen", 1089],
    ["Danny Frazier", 1089],
    ["Kaleigh Fitzgerald", 1085],
    ["Rogelio Douglas", 1083],
    ["Nyasia Salinas", 1081],
    ["Makhi Barton", 1080],
    ["Veronica Pace", 1079],
    ["Zachariah Lucero", 1077],
    ["Aracely Vincent", 1076],
    ["Cedric Vazquez", 1070],
    ["Dakota Mercado", 1067],
    ["Taylor Kline", 1067],
    ["Sammy Rivers", 1067],
]
most_active_users = [
    [3, [_most_active_n_users[:3]]],
    *[[n, _most_active_n_users[:n]] for n in choices(range(1, 101), k=10)],
]

_least_watched_n_categories = [
    "Film & Animation",
    "Howto & Style",
    "Entertainment",
    "Comedy",
    "People & Blogs",
    "Autos & Vehicles",
    "Pets & Animals",
    "Travel & Events",
    "Nonprofits & Activism",
    "Sports",
    "Science & Technology",
    "Gaming",
    "News & Politics",
    "Music",
    "Education",
]
least_watched_categories = [
    [1, [_least_watched_n_categories[0]]],
    *[[n, _least_watched_n_categories[:n]] for n in choices(range(1, 11), k=5)],
]
