# create your docker-compose here
version: "3.9"
services:
  flask-app:
    container_name: library
    build: .
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - db
    env_file: .env
    restart: always
  db:
    container_name: library-db
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - backend
    env_file: .env
    restart: always
networks:
  backend:
    driver: bridge
    name: backend
